import { makeStyles } from "@material-ui/core/styles";

export const styleItem2Sub1 = makeStyles((theme) => ({
  modal: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  paper: {
    backgroundColor: theme.palette.background.paper,
    boxShadow: theme.shadows[5],
    outline: "0",
    borderRadius: "5px",
  },
  modalContent: {
    display: "flex",
    flexDirection: "column",
    border: "none",
    padding: "20px 20px",
    justifyContent: "center",
    alignItems: "center",
    width: "600px",
    height: "400px",
  },
  close: {
    marginLeft: "auto",
    background: "#eeeeee",
    cursor: "pointer",
    width: "30px",
    height: "30px",
    borderRadius: "50%",
    textAlign: "center",
    lineHeight: "30px",
    fontSize: "1.5em",
  },
  root: {
    display: "flex",
    flexDirection: "column",
    position: "relative",
  },
  sec: {
    borderBottom: "1px solid rgba(0,0,0,0.2)",
    padding: "30px 0",
    width: "100%",
  },
  tags: {
    display: "flex",
    flexWrap: "wrap",
    "& div": {
      border: "1px solid #5094e7",
      color: "#5094e7",
      padding: "5px 15px",
      textAlign: "center",
      borderRadius: "5px",
      marginRight: "10px",
    },
  },
  field: {
    marginBottom: "10px",
    fontSize: "0.9em",
    color: "#333333",
    fontWeight: "500",
    textTransform: "uppercase",
  },
  value: {
    background: "white",
    width: "250px",
    borderRadius: "5px",
    border: "1px solid #cccccc",
    marginRight: "15px",
    color: "#828282",
    marginBottom: "15px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    padding: "5px 10px",
  },
  valueShort: {
    background: "white",
    width: "250px",
    borderRadius: "5px",
    border: "1px solid #cccccc",
    marginRight: "15px",
    color: "#828282",
    marginBottom: "15px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    padding: "5px 10px",
    width: "200px",
  },
  option: {
    height: "25px",
    border: "2px solid green",
  },
  col: {
    display: "flex",
    paddingBottom: "5px",
  },
  amenities: {
    display: "flex",
    marginBottom: "5px",
    padding: "8px 0",
  },
  amenitie: {
    marginRight: "10px",
  },
  aImage: {
    width: "150px",
    height: "auto",
  },
  toggleSwitch: {
    position: "absolute",
    display: "flex",
    alignItems: "center",
    top: "-34px",
    right: "10px",
  },
  switchLabel: {
    display: "flex",
    alignItems: "center",
  },
  switchSpan: {
    marginRight: "10px",
  },
  saveButton: {
    background: "#5094e7",
    color: "white",
    border: "none",
    padding: "0px 10px",
    height: "30px",
    width: "100px",
    borderRadius: "5px",
    cursor: "pointer",
    marginTop: "20px",
  },
  workplaceImageBox: {
    display: "flex",
  },
  workplaceImage: {
    width: "250px",
    height: "180px",
    marginRight: "10px",
    marginBottom: "10px",
    borderRadius: "10px",
  },
  dropDown: {
    width: "250px",
    marginRight: "15px",
    borderRadius: "5px",
  },
  placeholderDropdown: {
    width: "250px",
  },
}));
